; Configuration block for a PHP-FPM (FastCGI Process Manager) pool.
; Pool is a group of worker processes that listen for and execute incoming PHP requests 
; (like rendering a WordPress page).

[www] ; Name of the pool
user = www-data ; Sets the Linux user and 
group = www-data ; group that the PHP worker processes will run as.
listen = 9000 ; Listen for incoming PHP requests on TCP port 9000. (Matches Dockerfile)
listen.owner = www-data
listen.group = www-data

; Process Management
; This section controls how PHP-FPM manages its worker processes to handle website traffic.
pm = dynamic ; Tells PHP-FPM to dynamically scale the number of worker processes
pm.max_children = 5 ; The maximum number of simultaneous PHP worker
pm.start_servers = 2 ; Number of worker processes that PHP-FPM spawns
pm.min_spare_servers = 1 ; The minimum number of idle worker processes PHP-FPM must keep alive in the background.
pm.max_spare_servers = 3 ; Maximum
